name: build

on: [pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements_dev.txt
    - name: Build package
      run: |
        make build
    - uses: actions/upload-artifact@v2
      with:
        name: windows slime
        path: dist/

  build-mac:
    runs-on: macos-10.15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements_dev.txt
    - name: Build package
      run: |
        make build
    - uses: actions/upload-artifact@v2
      with:
        name: mac slime
        path: dist/slime.app
